/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package scientificcalculator;

/**
 *
 * @author Imoghome Blessings
 */
public class ScientificCalc extends javax.swing.JFrame {
    double firstNum;
    double secondNum;
    String operation;
    double result;
    /**
     * Creates new form ScientificCalc
     */
    public ScientificCalc() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtDisplay2 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtxtDisplay = new javax.swing.JTextArea();
        jRadioButtonON = new javax.swing.JRadioButton();
        jRadioButtonOFF = new javax.swing.JRadioButton();
        jButtonlog = new javax.swing.JButton();
        jButtonX2 = new javax.swing.JButton();
        jButtonXY = new javax.swing.JButton();
        jButtonRund = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jButtonDiv = new javax.swing.JButton();
        jButtonMinus = new javax.swing.JButton();
        jButtonExp = new javax.swing.JButton();
        jButtonlnx = new javax.swing.JButton();
        jButtonX3 = new javax.swing.JButton();
        jButtonEX = new javax.swing.JButton();
        jButtonBin = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButtonDot = new javax.swing.JButton();
        jButtonSin = new javax.swing.JButton();
        jButtonSinh = new javax.swing.JButton();
        jButtonMod = new javax.swing.JButton();
        jButtonOct = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton0 = new javax.swing.JButton();
        jButtonCos = new javax.swing.JButton();
        jButtonCosh = new javax.swing.JButton();
        jButtonSqrtRt = new javax.swing.JButton();
        jButtonHex = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButtonPlusMinus = new javax.swing.JButton();
        jButtonTan = new javax.swing.JButton();
        jButtonTanh = new javax.swing.JButton();
        jButtonCubeRoot = new javax.swing.JButton();
        jButtonFactorial = new javax.swing.JButton();
        jButtonClear = new javax.swing.JButton();
        jButtonMultiplication = new javax.swing.JButton();
        jButtonPlus = new javax.swing.JButton();
        jButtonEquals = new javax.swing.JButton();

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Scientific Calculator");

        jtxtDisplay2.setBackground(new java.awt.Color(255, 255, 204));
        jtxtDisplay2.setColumns(20);
        jtxtDisplay2.setRows(5);
        jScrollPane1.setViewportView(jtxtDisplay2);

        jtxtDisplay.setBackground(new java.awt.Color(255, 255, 204));
        jtxtDisplay.setColumns(20);
        jtxtDisplay.setRows(5);
        jScrollPane3.setViewportView(jtxtDisplay);

        jRadioButtonON.setText("ON");
        jRadioButtonON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonONActionPerformed(evt);
            }
        });
        jRadioButtonON.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jRadioButtonONPropertyChange(evt);
            }
        });

        jRadioButtonOFF.setText("OFF");
        jRadioButtonOFF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonOFFActionPerformed(evt);
            }
        });

        jButtonlog.setText("log");
        jButtonlog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonlogActionPerformed(evt);
            }
        });

        jButtonX2.setText("x^2");
        jButtonX2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonX2ActionPerformed(evt);
            }
        });

        jButtonXY.setText("x^y");
        jButtonXY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonXYActionPerformed(evt);
            }
        });

        jButtonRund.setFont(new java.awt.Font("Segoe UI", 1, 8)); // NOI18N
        jButtonRund.setText("Rund");
        jButtonRund.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRundActionPerformed(evt);
            }
        });

        jButtonDelete.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonDelete.setText("DEL");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        jButtonDiv.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonDiv.setText("/");
        jButtonDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDivActionPerformed(evt);
            }
        });

        jButtonMinus.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonMinus.setText("-");
        jButtonMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMinusActionPerformed(evt);
            }
        });

        jButtonExp.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonExp.setText("exp");
        jButtonExp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExpActionPerformed(evt);
            }
        });

        jButtonlnx.setText("lnx");
        jButtonlnx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonlnxActionPerformed(evt);
            }
        });

        jButtonX3.setText("x^3");
        jButtonX3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonX3ActionPerformed(evt);
            }
        });

        jButtonEX.setText("e^x");
        jButtonEX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEXActionPerformed(evt);
            }
        });

        jButtonBin.setText("Bin");
        jButtonBin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBinActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton7.setText("7");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton4.setText("4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setText("1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButtonDot.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonDot.setText(".");
        jButtonDot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDotActionPerformed(evt);
            }
        });

        jButtonSin.setText("sin");
        jButtonSin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSinActionPerformed(evt);
            }
        });

        jButtonSinh.setText("sinh");
        jButtonSinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSinhActionPerformed(evt);
            }
        });

        jButtonMod.setText("%");
        jButtonMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModActionPerformed(evt);
            }
        });

        jButtonOct.setText("Oct");
        jButtonOct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOctActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton8.setText("8");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton5.setText("5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setText("2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton0.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton0.setText("0");
        jButton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton0ActionPerformed(evt);
            }
        });

        jButtonCos.setText("cos");
        jButtonCos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCosActionPerformed(evt);
            }
        });

        jButtonCosh.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jButtonCosh.setText("cosh");
        jButtonCosh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCoshActionPerformed(evt);
            }
        });

        jButtonSqrtRt.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jButtonSqrtRt.setText("SqrRt");
        jButtonSqrtRt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSqrtRtActionPerformed(evt);
            }
        });

        jButtonHex.setText("Hex");
        jButtonHex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHexActionPerformed(evt);
            }
        });

        jButton9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton9.setText("9");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton6.setText("6");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton3.setText("3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButtonPlusMinus.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonPlusMinus.setText("+/-");
        jButtonPlusMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlusMinusActionPerformed(evt);
            }
        });

        jButtonTan.setText("tan");
        jButtonTan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTanActionPerformed(evt);
            }
        });

        jButtonTanh.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jButtonTanh.setText("tanh");
        jButtonTanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTanhActionPerformed(evt);
            }
        });

        jButtonCubeRoot.setText("CbR");
        jButtonCubeRoot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCubeRootActionPerformed(evt);
            }
        });

        jButtonFactorial.setText("n!");
        jButtonFactorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFactorialActionPerformed(evt);
            }
        });

        jButtonClear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonClear.setText("AC");
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });

        jButtonMultiplication.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonMultiplication.setText("*");
        jButtonMultiplication.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMultiplicationActionPerformed(evt);
            }
        });

        jButtonPlus.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonPlus.setText("+");
        jButtonPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlusActionPerformed(evt);
            }
        });

        jButtonEquals.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonEquals.setText("=");
        jButtonEquals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEqualsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButtonX2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButtonXY, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButtonlog, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButtonRund, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButtonDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButtonExp, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButtonX3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButtonEX, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButtonlnx, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButtonBin, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButtonDot, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButtonSinh, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButtonMod, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButtonSin, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButtonOct, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton0, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButtonCosh, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButtonSqrtRt, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButtonCos, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButtonHex, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButtonPlusMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButtonTanh, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButtonCubeRoot, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButtonTan, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButtonFactorial, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButtonClear, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButtonMultiplication, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButtonPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButtonEquals, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(jScrollPane3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButtonON, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButtonOFF, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButtonMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonON)
                            .addComponent(jRadioButtonOFF))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonlog, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonX2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonXY, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonRund, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonExp, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonlnx, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonX3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonEX, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonBin, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonDot, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jButtonCos, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButtonCosh, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButtonSqrtRt, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButtonHex, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButtonPlusMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jButtonSin, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButtonSinh, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButtonMod, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButtonOct, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton0, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jButtonTan, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButtonTanh, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButtonCubeRoot, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButtonFactorial, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButtonClear, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButtonMultiplication, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButtonPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButtonEquals, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonlogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonlogActionPerformed
        // TODO add your handling code here:
        double ope = Double.parseDouble(String.valueOf(jtxtDisplay.getText()));
        jtxtDisplay2.setText("log(" + jtxtDisplay.getText()+ ")");
        ope = Math.log10(ope);
        jtxtDisplay.setText(String.valueOf(ope));
    }//GEN-LAST:event_jButtonlogActionPerformed

    private void jButtonlnxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonlnxActionPerformed
        // TODO add your handling code here:
        double ope = Double.parseDouble(jtxtDisplay.getText());
        jtxtDisplay2.setText("ln(" + String.valueOf(ope) + ")");
        ope = Math.log(ope);
        jtxtDisplay.setText(String.valueOf(ope));
    }//GEN-LAST:event_jButtonlnxActionPerformed

    private void jButtonSinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSinActionPerformed
        // TODO add your handling code here:
        double ope = Double.parseDouble(String.valueOf(jtxtDisplay.getText()));
        jtxtDisplay2.setText("(sin)(" + jtxtDisplay.getText()+ ")");
        ope = ope * 0.0174532925;
        ope = Math.sin(ope);
        jtxtDisplay.setText(String.valueOf(ope));
    }//GEN-LAST:event_jButtonSinActionPerformed

    private void jButtonCosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCosActionPerformed
        // TODO add your handling code here:
        double ope = Double.parseDouble(String.valueOf(jtxtDisplay.getText()));
        jtxtDisplay2.setText("(cos)(" + jtxtDisplay.getText()+ ")");
        ope = ope * 0.0174532925;
        ope = Math.cos(ope);
        jtxtDisplay.setText(String.valueOf(ope));
    }//GEN-LAST:event_jButtonCosActionPerformed

    private void jButtonTanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTanActionPerformed
        // TODO add your handling code here:
        double ope = Double.parseDouble(String.valueOf(jtxtDisplay.getText()));
        jtxtDisplay2.setText("(tan)(" + jtxtDisplay.getText()+ ")");
        ope = ope * 0.0174532925;
        ope = Math.tan(ope);
        jtxtDisplay.setText(String.valueOf(ope));
    }//GEN-LAST:event_jButtonTanActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        String iNum = jtxtDisplay.getText()+jButton7.getText();
        jtxtDisplay.setText(iNum);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButtonBinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBinActionPerformed
        // TODO add your handling code here:
        int a = Integer.parseInt(jtxtDisplay.getText());
        jtxtDisplay2.setText("Bin(" + Integer.toString(a) + ")" );
        jtxtDisplay.setText(Integer.toString(a, 2));
    }//GEN-LAST:event_jButtonBinActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        // TODO add your handling code here:
        String del = null;
        if (jtxtDisplay.getText().length() > 0)
        {
            StringBuilder strB = new StringBuilder(jtxtDisplay.getText());
            strB.deleteCharAt(jtxtDisplay.getText().length()-1);
            del = strB.toString();
            jtxtDisplay.setText(del);
        }
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        String iNum = jtxtDisplay.getText()+jButton8.getText();
        jtxtDisplay.setText(iNum);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButtonX2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonX2ActionPerformed
        // TODO add your handling code here:
        double ope = Double.parseDouble(String.valueOf(jtxtDisplay.getText()));
        jtxtDisplay2.setText(String.valueOf(jtxtDisplay.getText()) + "^2");
        ope = (ope * ope);
        jtxtDisplay.setText(String.valueOf(ope));
    }//GEN-LAST:event_jButtonX2ActionPerformed

    private void jButtonX3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonX3ActionPerformed
        // TODO add your handling code here:
        double ope = Double.parseDouble(String.valueOf(jtxtDisplay.getText()));
        jtxtDisplay2.setText(String.valueOf(jtxtDisplay.getText()) + "^3");
        ope = ope * ope * ope;
        jtxtDisplay.setText(String.valueOf(ope));
    }//GEN-LAST:event_jButtonX3ActionPerformed

    private void jButtonSinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSinhActionPerformed
        // TODO add your handling code here:
        double ope = Double.parseDouble(String.valueOf(jtxtDisplay.getText()));
        jtxtDisplay2.setText("(sinh)(" + jtxtDisplay.getText()+ ")");
        ope = Math.sinh(ope);
        jtxtDisplay.setText(String.valueOf(ope));
    }//GEN-LAST:event_jButtonSinhActionPerformed

    private void jButtonCoshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCoshActionPerformed
        // TODO add your handling code here:
        double ope = Double.parseDouble(String.valueOf(jtxtDisplay.getText()));
        jtxtDisplay2.setText("(cosh)(" + jtxtDisplay.getText()+ ")");
        ope = Math.cosh(ope);
        jtxtDisplay.setText(String.valueOf(ope));
    }//GEN-LAST:event_jButtonCoshActionPerformed

    private void jButtonTanhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTanhActionPerformed
        // TODO add your handling code here:
        double ope = Double.parseDouble(String.valueOf(jtxtDisplay.getText()));
        jtxtDisplay2.setText("(tanh)(" + jtxtDisplay.getText()+ ")");
        ope = Math.tanh(ope);
        jtxtDisplay.setText(String.valueOf(ope));
    }//GEN-LAST:event_jButtonTanhActionPerformed

    private void jButtonXYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonXYActionPerformed
        // TODO add your handling code here:
        firstNum = Double.parseDouble(jtxtDisplay.getText());
        jtxtDisplay.setText(null);
        operation = (" x^y ");
        jtxtDisplay2.setText(String.valueOf(firstNum) + "^(");
    }//GEN-LAST:event_jButtonXYActionPerformed

    private void jButtonEXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEXActionPerformed
        // TODO add your handling code here:
        double ope = Math.exp(Double.parseDouble((jtxtDisplay.getText())));
        jtxtDisplay2.setText("e^(" + jtxtDisplay.getText() + ")");
        jtxtDisplay.setText("");
        jtxtDisplay.setText(jtxtDisplay.getText() + ope);
    }//GEN-LAST:event_jButtonEXActionPerformed

    private void jButtonModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModActionPerformed
        // TODO add your handling code here:
        firstNum = Double.parseDouble(jtxtDisplay.getText());
        jtxtDisplay.setText(null);
        operation = (" % ");
        jtxtDisplay2.setText(String.valueOf(firstNum) + "%");
    }//GEN-LAST:event_jButtonModActionPerformed

    private void jButtonSqrtRtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSqrtRtActionPerformed
        // TODO add your handling code here:
        double ope = Double.parseDouble(String.valueOf(jtxtDisplay.getText()));
        jtxtDisplay2.setText("(Square Root)(" + jtxtDisplay.getText()+ ")");
        ope = Math.sqrt(ope);
        jtxtDisplay.setText(String.valueOf(ope));
    }//GEN-LAST:event_jButtonSqrtRtActionPerformed

    private void jButtonCubeRootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCubeRootActionPerformed
        // TODO add your handling code here:
        double ope = Double.parseDouble(String.valueOf(jtxtDisplay.getText()));
        jtxtDisplay2.setText("(Cube Root)(" + jtxtDisplay.getText()+ ")");
        ope = Math.cbrt(ope);
        jtxtDisplay.setText(String.valueOf(ope));
    }//GEN-LAST:event_jButtonCubeRootActionPerformed

    private void jButtonRundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRundActionPerformed
        // TODO add your handling code here:
        double ope = Double.parseDouble(String.valueOf(jtxtDisplay.getText()));
        jtxtDisplay2.setText("(Rund)(" + jtxtDisplay.getText()+ ")");
        ope = Math.round(ope);
        jtxtDisplay.setText(String.valueOf(ope));
    }//GEN-LAST:event_jButtonRundActionPerformed

    private void jButtonOctActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOctActionPerformed
        // TODO add your handling code here:
        int a = Integer.parseInt(jtxtDisplay.getText());
        jtxtDisplay2.setText("Oct(" + Integer.toString(a) + ")" );
        jtxtDisplay.setText(Integer.toString(a, 8));
    }//GEN-LAST:event_jButtonOctActionPerformed

    private void jButtonHexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHexActionPerformed
        // TODO add your handling code here:
        int a = Integer.parseInt(jtxtDisplay.getText());
        jtxtDisplay2.setText("Hex(" + Integer.toString(a) + ")" );
        jtxtDisplay.setText(Integer.toString(a, 16));
    }//GEN-LAST:event_jButtonHexActionPerformed

    private void jButtonFactorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFactorialActionPerformed
        // TODO add your handling code here:
        double ope = Double.parseDouble(jtxtDisplay.getText());
        double fact = 1;
        jtxtDisplay2.setText(jtxtDisplay.getText() + "!");
        while (ope != 0)
        {
            fact = fact * ope;
            ope--;
        }
        jtxtDisplay.setText("");
        jtxtDisplay.setText(jtxtDisplay.getText() + fact);
    }//GEN-LAST:event_jButtonFactorialActionPerformed

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        // TODO add your handling code here:
        jtxtDisplay2.setText("");
        jtxtDisplay.setText("");
    }//GEN-LAST:event_jButtonClearActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String iNum = jtxtDisplay.getText()+jButton4.getText();
        jtxtDisplay.setText(iNum);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButtonMultiplicationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMultiplicationActionPerformed
        // TODO add your handling code here:
        firstNum = Double.parseDouble((jtxtDisplay.getText()));
        jtxtDisplay.setText(null);
        operation = (" * ");
        jtxtDisplay2.setText(String.valueOf(firstNum)+"*");
    }//GEN-LAST:event_jButtonMultiplicationActionPerformed

    private void jButtonMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMinusActionPerformed
        // TODO add your handling code here:
        firstNum = Double.parseDouble((jtxtDisplay.getText()));
        jtxtDisplay.setText(null);
        operation = (" - ");
        jtxtDisplay2.setText(String.valueOf(firstNum)+"-");
    }//GEN-LAST:event_jButtonMinusActionPerformed

    private void jButtonPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlusActionPerformed
        // TODO add your handling code here:
        firstNum = Double.parseDouble((jtxtDisplay.getText()));
        jtxtDisplay.setText(null);
        operation = (" + ");
        jtxtDisplay2.setText(String.valueOf(firstNum)+"+");
    }//GEN-LAST:event_jButtonPlusActionPerformed

    private void jButtonExpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExpActionPerformed
        // TODO add your handling code here:
        double ope = Double.parseDouble(jtxtDisplay.getText());
        double exp = 10;
        double p;
        jtxtDisplay2.setText("10^(" + jtxtDisplay.getText() + ")");
        p = Math.pow(exp, ope);
        jtxtDisplay.setText("");
        jtxtDisplay2.setText(jtxtDisplay.getText()+ p );
    }//GEN-LAST:event_jButtonExpActionPerformed

    private void jButtonPlusMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlusMinusActionPerformed
        // TODO add your handling code here:
        Double ope = Double.valueOf(String.valueOf(jtxtDisplay.getText()));
        ope = ope * (-1);
        jtxtDisplay.setText(String.valueOf(ope));
    }//GEN-LAST:event_jButtonPlusMinusActionPerformed

    private void jButtonEqualsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEqualsActionPerformed
        // TODO add your handling code here:
        String answer;
        secondNum = Double.parseDouble(jtxtDisplay.getText());
        if ((" * ").equals(operation))
        {
            result = firstNum * secondNum;
            answer = String.format("%.2f", result);
            jtxtDisplay2.setText(String.valueOf(firstNum)+("*")+String.valueOf(secondNum));
            jtxtDisplay.setText(answer);
        } 
        else if ((" / ").equals(operation))
        {
            result = firstNum / secondNum;
            answer = String.format("%.2f", result);
            jtxtDisplay2.setText(String.valueOf(firstNum)+("/")+String.valueOf(secondNum));
            jtxtDisplay.setText(answer);
        }
        else if ((" + ").equals(operation))
        {
            result = firstNum + secondNum;
            answer = String.format("%.2f", result);
            jtxtDisplay2.setText(String.valueOf(firstNum)+("+")+String.valueOf(secondNum));
            jtxtDisplay.setText(answer);
        } 
        else if ((" - ").equals(operation))
        {
            result = firstNum - secondNum;
            answer = String.format("%.2f", result);
            jtxtDisplay2.setText(String.valueOf(firstNum)+("-")+String.valueOf(secondNum));
            jtxtDisplay.setText(answer);
        }
        else if ((" % ").equals(operation))
        {
            result = firstNum % secondNum;
            answer = String.format("%.2f", result);
            jtxtDisplay2.setText(String.valueOf(firstNum)+("%")+String.valueOf(secondNum));
            jtxtDisplay.setText(answer);
        }
        else if ((" x^y ").equals(operation))
        {
            result = 1;
            for (int i = 0; i < secondNum; i++)
            {
                result = firstNum * result;
            }
            jtxtDisplay2.setText(String.valueOf(firstNum)+"^"+String.valueOf(secondNum));
            answer = String.format("%.2f", result);
            jtxtDisplay.setText(answer);
        }
    }//GEN-LAST:event_jButtonEqualsActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        String iNum = jtxtDisplay.getText()+jButton9.getText();
        jtxtDisplay.setText(iNum);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        String iNum = jtxtDisplay.getText()+jButton5.getText();
        jtxtDisplay.setText(iNum);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        String iNum = jtxtDisplay.getText()+jButton6.getText();
        jtxtDisplay.setText(iNum);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String iNum = jtxtDisplay.getText()+jButton1.getText();
        jtxtDisplay.setText(iNum);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String iNum = jtxtDisplay.getText()+jButton2.getText();
        jtxtDisplay.setText(iNum);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String iNum = jtxtDisplay.getText()+jButton3.getText();
        jtxtDisplay.setText(iNum);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton0ActionPerformed
        // TODO add your handling code here:
        String iNum = jtxtDisplay.getText()+jButton0.getText();
        jtxtDisplay.setText(iNum);
    }//GEN-LAST:event_jButton0ActionPerformed

    private void jButtonDotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDotActionPerformed
        // TODO add your handling code here:
        if (!jtxtDisplay.getText().contains("."))
        {
            jtxtDisplay.setText(jtxtDisplay.getText()+jButtonDot.getText());
        }
    }//GEN-LAST:event_jButtonDotActionPerformed

    private void jButtonDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDivActionPerformed
        // TODO add your handling code here:
        firstNum = Double.parseDouble((jtxtDisplay.getText()));
        jtxtDisplay.setText(null);
        operation = (" / ");
        jtxtDisplay2.setText(String.valueOf(firstNum)+"/");
    }//GEN-LAST:event_jButtonDivActionPerformed

    private void jRadioButtonONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonONActionPerformed
        // TODO add your handling code here:
        jButton1.setEnabled(true);
        jButton2.setEnabled(true);
        jButton3.setEnabled(true);
        jButton4.setEnabled(true);
        jButton5.setEnabled(true);
        jButton6.setEnabled(true);
        jButton7.setEnabled(true);
        jButton8.setEnabled(true);
        jButton9.setEnabled(true);
        jButton0.setEnabled(true);
        jButtonlog.setEnabled(true);
        jButtonlnx.setEnabled(true);
        jButtonSin.setEnabled(true);
        jButtonCos.setEnabled(true);
        jButtonTan.setEnabled(true);
        jButtonX2.setEnabled(true);
        jButtonX3.setEnabled(true);
        jButtonSinh.setEnabled(true);
        jButtonCosh.setEnabled(true);
        jButtonTanh.setEnabled(true);
        jButtonXY.setEnabled(true);
        jButtonEX.setEnabled(true);
        jButtonMod.setEnabled(true);
        jButtonSqrtRt.setEnabled(true);
        jButtonCubeRoot.setEnabled(true);
        jButtonRund.setEnabled(true);
        jButtonBin.setEnabled(true);
        jButtonOct.setEnabled(true);
        jButtonHex.setEnabled(true);
        jButtonFactorial.setEnabled(true);
        jButtonDelete.setEnabled(true);
        jButtonClear.setEnabled(true);
        jButtonDiv.setEnabled(true);
        jButtonMinus.setEnabled(true);
        jButtonMultiplication.setEnabled(true);
        jButtonPlus.setEnabled(true);
        jButtonExp.setEnabled(true);
        jButtonDot.setEnabled(true);
        jButtonPlusMinus.setEnabled(true);
        jButtonEquals.setEnabled(true);
        jtxtDisplay.setEnabled(true);
        jtxtDisplay2.setEnabled(true);    
              
    }//GEN-LAST:event_jRadioButtonONActionPerformed

    private void jRadioButtonOFFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonOFFActionPerformed
        // TODO add your handling code here:
        jtxtDisplay.setEnabled(false);
        jtxtDisplay2.setEnabled(false);
        jButton1.setEnabled(false);
        jButton2.setEnabled(false);
        jButton3.setEnabled(false);
        jButton4.setEnabled(false);
        jButton5.setEnabled(false);
        jButton6.setEnabled(false);
        jButton7.setEnabled(false);
        jButton8.setEnabled(false);
        jButton9.setEnabled(false);
        jButton0.setEnabled(false);
        jButtonlog.setEnabled(false);
        jButtonlnx.setEnabled(false);
        jButtonSin.setEnabled(false);
        jButtonCos.setEnabled(false);
        jButtonTan.setEnabled(false);
        jButtonX2.setEnabled(false);
        jButtonX3.setEnabled(false);
        jButtonSinh.setEnabled(false);
        jButtonCosh.setEnabled(false);
        jButtonTanh.setEnabled(false);
        jButtonXY.setEnabled(false);
        jButtonEX.setEnabled(false);
        jButtonMod.setEnabled(false);
        jButtonSqrtRt.setEnabled(false);
        jButtonCubeRoot.setEnabled(false);
        jButtonRund.setEnabled(false);
        jButtonBin.setEnabled(false);
        jButtonOct.setEnabled(false);
        jButtonHex.setEnabled(false);
        jButtonFactorial.setEnabled(false);
        jButtonDelete.setEnabled(false);
        jButtonClear.setEnabled(false);
        jButtonDiv.setEnabled(false);
        jButtonMinus.setEnabled(false);
        jButtonMultiplication.setEnabled(false);
        jButtonPlus.setEnabled(false);
        jButtonExp.setEnabled(false);
        jButtonDot.setEnabled(false);
        jButtonPlusMinus.setEnabled(false);
        jButtonEquals.setEnabled(false);
        jtxtDisplay.setText("");
        jtxtDisplay2.setText("");   
    }//GEN-LAST:event_jRadioButtonOFFActionPerformed

    private void jRadioButtonONPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jRadioButtonONPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonONPropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScientificCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScientificCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScientificCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScientificCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ScientificCalc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.JButton jButton0;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonBin;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonCos;
    private javax.swing.JButton jButtonCosh;
    private javax.swing.JButton jButtonCubeRoot;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonDiv;
    private javax.swing.JButton jButtonDot;
    private javax.swing.JButton jButtonEX;
    private javax.swing.JButton jButtonEquals;
    private javax.swing.JButton jButtonExp;
    private javax.swing.JButton jButtonFactorial;
    private javax.swing.JButton jButtonHex;
    private javax.swing.JButton jButtonMinus;
    private javax.swing.JButton jButtonMod;
    private javax.swing.JButton jButtonMultiplication;
    private javax.swing.JButton jButtonOct;
    private javax.swing.JButton jButtonPlus;
    private javax.swing.JButton jButtonPlusMinus;
    private javax.swing.JButton jButtonRund;
    private javax.swing.JButton jButtonSin;
    private javax.swing.JButton jButtonSinh;
    private javax.swing.JButton jButtonSqrtRt;
    private javax.swing.JButton jButtonTan;
    private javax.swing.JButton jButtonTanh;
    private javax.swing.JButton jButtonX2;
    private javax.swing.JButton jButtonX3;
    private javax.swing.JButton jButtonXY;
    private javax.swing.JButton jButtonlnx;
    private javax.swing.JButton jButtonlog;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonOFF;
    private javax.swing.JRadioButton jRadioButtonON;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jtxtDisplay;
    private javax.swing.JTextArea jtxtDisplay2;
    // End of variables declaration//GEN-END:variables
}
